apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: marmazeevdmitriy/backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "corpmail"
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: STORAGE_HOST
              value: "storage"
            - name: STORAGE_PORT
              value: "9000"
            - name: STORAGE_ACCESS_KEY
              value: "minioadmin"
            - name: STORAGE_SECRET_KEY
              value: "minioadmin"
